CREATE TABLE CATEGORY (
      ID INT NOT NULL
     , NAME VARCHAR(100)
     , PRIMARY KEY (ID)
);

CREATE TABLE BOOKS (
    ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    TITLE VARCHAR(60) NOT NULL,
    ISBN VARCHAR(10) NOT NULL,
    PRICE DECIMAL(4,2),
    PRIMARY KEY (ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (CATEGORY_ID)
                  REFERENCES CATEGORY (ID)
);